### ISSUE TITLE
class interceptor causes lag

### ISSUE THREAD

**Issue by MicleBrick** [bergerhealer/Light-Cleaner#9]
light cleaner has some sort of class interceptor, I noticed by sampling that it constantly causes lag and now it froze the server for 35 seconds:

https://gist.github.com/Miclebrick/7e844039409d0c75d744665d0776aaa9

I have reload on load chunks off so it shouldn't be doing anything right now

**Comment by Miclebrick** [comment]
https://gist.github.com/Miclebrick/2c7c759ac50ad5b5307b53e8a618420e
 now it causes freezes...

**Comment by bergerkiller** [comment]
Both issues are not part of light cleaner itself.

First one: BKCommonLib has a hook listening to getMobsFor. Only MyWorlds actually uses that hook. When it is not used, all it does is pass the call on to the underlying implementation. If the server froze during getMobsFor, it was caused by the server logic it is initiating:
```
[09:11:33 ERROR]: 		org.bukkit.craftbukkit.v1_12_R1.generator.CustomChunkGenerator.getMobsFor(CustomChunkGenerator.java:218)
[09:11:33 ERROR]: co.aikar.timings.TimedChunkGenerator.getMobsFor(TimedChunkGenerator.java:111)
```

Second: its not causing the freeze, but it certainly is making it worse. BKCommonLib registers a listener on the server to detect entities being added and removed. Some plugins require this logic, LC is not one of them. Unfortunately this listener also listens to block physics events. It looks like a whole lot of them happened in fast succession (rapid fire spread?). The bug here is that the lookup logic for the method to call (which should be a no-op, it is not actually listened to) is too slow. So you're seeing the method equals show up. This is something I will definitely have to fix in mountiplex/BKCommonLib.
